services:
  backend:
    build:
      context: ./backend
    environment:
      - ATLAS_URI=${ATLAS_URI}
      - DB_NAME=${DB_NAME}
    volumes:
      - ./backend:/app
    ports:
      - "${BACKEND_PORT}:8080"

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_BACKEND_URI=${BACKEND_URI}
    ports:
      - "${FRONTEND_PORT}:5173"
    command: npm run dev

volumes:
  app_todo:
